### ISSUE TITLE
Guppy fails when used in a non-module scope

### ISSUE THREAD

**Issue by doug-q** [CQCL/guppylang#148]
I expect the following to print a json representation of the generated hugr.
```
if __name__ == "__main__":
    from guppylang.decorator import guppy
    from guppylang import quantum
    guppy.load(quantum)
    @guppy
    def teleport(src: Qubit, tgt: Qubit) -> Qubit:
        # Create ancilla and entangle it with src and tgt
        tmp = Qubit()
        tmp, tgt = cx(h(tmp), tgt)
        src, tmp = cx(src, tmp)

        # Apply classical corrections
        if measure(h(src)):
            tgt = z(tgt)
        if measure(tmp):
            tgt = x(tgt)
        return tgt

    print(guppy.compile_module().serialize())
```

Instead I see:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/doug/code/eldarion/python/go.py", line 49, in <module>
    def teleport(src: Qubit, tgt: Qubit) -> Qubit:
                      ^^^^^
NameError: name 'Qubit' is not defined. Did you mean: 'quit'?
```

I am interested in carefully controlling which extensions are loaded into guppy because I want to swap out the quantum extension. Is it possible to support this?

**Comment by doug-q** [comment]
Hold up, the obvious fix `from guppylang import quantum, Qubit` does work. This is probably nonsense, will update or close.
