### ISSUE TITLE
Pytest hangs if when `GuppyError` is thrown

### ISSUE THREAD

**Issue by mark-koch** [CQCL/guppylang#569]
E.g. when trying to run the test

```python
def test_guppy_error(validate):
    module = GuppyModule("test")
    
    @guppy(module)
    def bad(x: int) -> int:
        return y  # y not defined, so this will error

    validate(module.compile())
```

pytest will just hang. This seems to happen whenever the compiler throws a `GuppyError`. However, `GuppyTypeError` works fine?!

This seems to be the reason for #565

**Comment by acl-cqc** [comment]
I added a non-compiling test and also saw a hang, repeated-Ctrl-C produced this stacktrace:
```
Traceback (most recent call last):
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/main.py", line 283, in wrap_session
    session.exitstatus = doit(config, session) or 0
                         ~~~~^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/main.py", line 337, in _main
    config.hook.pytest_runtestloop(session=session)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/logging.py", line 803, in pytest_runtestloop
    return (yield)  # Run all the tests.
            ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/terminal.py", line 673, in pytest_runtestloop
    result = yield
             ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/main.py", line 362, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/warnings.py", line 112, in pytest_runtest_protocol
    return (yield)
            ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/assertion/__init__.py", line 176, in pytest_runtest_protocol
    return (yield)
            ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/unittest.py", line 429, in pytest_runtest_protocol
    res = yield
          ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/faulthandler.py", line 88, in pytest_runtest_protocol
    return (yield)
            ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/runner.py", line 113, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/runner.py", line 132, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/runner.py", line 244, in call_and_report
    report: TestReport = ihook.pytest_runtest_makereport(item=item, call=call)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/tmpdir.py", line 318, in pytest_runtest_makereport
    rep = yield
          ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/skipping.py", line 269, in pytest_runtest_makereport
    rep = yield
          ^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/runner.py", line 368, in pytest_runtest_makereport
    return TestReport.from_item_and_call(item, call)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/reports.py", line 376, in from_item_and_call
    longrepr = item.repr_failure(excinfo)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/python.py", line 1669, in repr_failure
    return self._repr_failure_py(excinfo, style=style)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/nodes.py", line 456, in _repr_failure_py
    return excinfo.getrepr(
           ~~~~~~~~~~~~~~~^
        funcargs=True,
        ^^^^^^^^^^^^^^
    ...<5 lines>...
        truncate_args=truncate_args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 690, in getrepr
    return fmt.repr_excinfo(self)
           ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 1058, in repr_excinfo
    reprtraceback = self.repr_traceback(excinfo_)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 992, in repr_traceback
    self.repr_traceback_entry(entry, excinfo if last == entry else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 937, in repr_traceback_entry
    reprargs = self.repr_args(entry) if not short else None
               ~~~~~~~~~~~~~~^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 838, in repr_args
    str_repr = saferepr(argvalue)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_io/saferepr.py", line 111, in saferepr
    return SafeRepr(maxsize, use_ascii).repr(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_io/saferepr.py", line 62, in repr
    s = super().repr(x)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 60, in repr
    return self.repr1(x, self.maxlevel)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 70, in repr1
    return self.repr_instance(x, level)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_io/saferepr.py", line 73, in repr_instance
    s = repr(x)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 9, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 12, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alanlawrence/repos/guppylang/.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ~~~~~~~~~~~~^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/main.py", line 297, in wrap_session
    config.hook.pytest_keyboard_interrupt(excinfo=excinfo)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/terminal.py", line 932, in pytest_keyboard_interrupt
    self._keyboardinterrupt_memo = excinfo.getrepr(funcargs=True)
                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 690, in getrepr
    return fmt.repr_excinfo(self)
           ~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 1058, in repr_excinfo
    reprtraceback = self.repr_traceback(excinfo_)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 992, in repr_traceback
    self.repr_traceback_entry(entry, excinfo if last == entry else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 937, in repr_traceback_entry
    reprargs = self.repr_args(entry) if not short else None
               ~~~~~~~~~~~~~~^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_code/code.py", line 838, in repr_args
    str_repr = saferepr(argvalue)
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_io/saferepr.py", line 111, in saferepr
    return SafeRepr(maxsize, use_ascii).repr(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_io/saferepr.py", line 62, in repr
    s = super().repr(x)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 60, in repr
    return self.repr1(x, self.maxlevel)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 70, in repr1
    return self.repr_instance(x, level)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/alanlawrence/repos/guppylang/.venv/lib/python3.13/site-packages/_pytest/_io/saferepr.py", line 73, in repr_instance
    s = repr(x)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 9, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 12, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/reprlib.py", line 21, in wrapper
    result = user_function(self)
  File "<string>", line 10, in __repr__
KeyboardInterrupt
```

**Comment by ss2165** [comment]
Another similar example in commit e3457f898a7a9e6f8ec0df02abfc0820b4920bc6

**Comment by mark-koch** [comment]
I figured it out! Here is a test that reproduces the issue:

```python
def test_hand(validate):
    module = GuppyModule("test")

    @guppy(module)
    def test() -> int:
        return a  # Intentionally use an undefined variable

    validate(module.compile())
```

The problem is that pytest tries to be "helpful" when an error occurs in a test, so it tries to print the values of variables that are in scope where the exception is thrown. In the case above, the compiler section that emits this error has `globals` in scope. When printing `globals`, it also tries to print `globals.python_scope` which contains all python variables that are in scope *in the test itself*, including the `module` variable that again holds a reference to the same globals. Therefore, the `repr(globals)` call never terminates and pytest just hangs.

I think we should just exclude `python_scope` from being outputted by `repr` which should solve this problem
