### ISSUE TITLE
`guppylang.error.InternalGuppyError`: Couldn't obtain a port for a variable

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/guppylang#607]
Possible this is fixed on main already, just making an issue in case it isn't.

I have a simple function which adds controlled unitaries in a loop for quantum phase estimation.

```python
@guppy
def add_CU(qs: array[qubit, 6]) -> None:
    for qubit_index in range(4):
        control_index: int = 3 - qubit_index
        for _ in range(2**qubit_index):
            controlled_u(qs[control_index], qs[-2], qs[-1])
```

Where `controlled_u` is defined as follows....

```python
@guppy
def controlled_u(control: qubit, target1: qubit, target2: qubit) -> None:
    crz(control, target2, angle(-0.062))
    toffoli(control, target1, target2)
    crz(control, target2, angle(-0.063))
    toffoli(control, target1, target2)
    crz(control, target1, angle(0.188))
```

When I try to compile this I get

```
Traceback (most recent call last):
  File "/Users/callum/work_projects/guppy-integration/notebooks/cannonical_qpe.py", line 91, in <module>
    runner = build_hsim(guppy.compile_module(), "QPE_EXP")
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/decorator.py", line 430, in compile_module
    return module.compile()
           ^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/error.py", line 181, in pretty_errors_wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/module.py", line 332, in compile
    next_def.compile_inner(ctx)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/definition/function.py", line 220, in compile_inner
    compile_global_func_def(self, self.func_def, globals)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/func_compiler.py", line 22, in compile_global_func_def
    cfg = compile_cfg(func.cfg, builder, builder.inputs(), globals)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/cfg_compiler.py", line 46, in compile_cfg
    blocks[bb] = compile_bb(bb, builder, bb == cfg.entry_bb, globals)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/cfg_compiler.py", line 83, in compile_bb
    dfg = StmtCompiler(globals).compile_stmts(bb.statements, dfg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/stmt_compiler.py", line 44, in compile_stmts
    self.visit(s)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/stmt_compiler.py", line 78, in visit_Expr
    self.expr_compiler.compile_row(node.value, self.dfg)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 83, in compile_row
    return [self.compile(e, dfg) for e in expr_to_row(expr)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 83, in <listcomp>
    return [self.compile(e, dfg) for e in expr_to_row(expr)]
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 74, in compile
    return self.visit(expr)
           ^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 340, in visit_GlobalCall
    args = [self.visit(arg) for arg in node.args]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 340, in <listcomp>
    args = [self.visit(arg) for arg in node.args]
            ^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 183, in visit_PlaceNode
    self.dfg[subscript.item] = self.visit(subscript.item_expr)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 185, in visit_PlaceNode
    return self.dfg[node.place]
           ~~~~~~~~^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/core.py", line 86, in __getitem__
    raise InternalGuppyError(f"Couldn't obtain a port for `{place}`")
guppylang.error.InternalGuppyError: Couldn't obtain a port for `control_index`
(guppy-integration) callum@Callums-MacBook-Pro notebooks % python cannonical_qpe.py 
Traceback (most recent call last):
  File "/Users/callum/work_projects/guppy-integration/notebooks/cannonical_qpe.py", line 91, in <module>
    runner = build_hsim(guppy.compile_module(), "QPE_EXP")
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/decorator.py", line 430, in compile_module
    return module.compile()
           ^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/error.py", line 181, in pretty_errors_wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/module.py", line 332, in compile
    next_def.compile_inner(ctx)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/definition/function.py", line 220, in compile_inner
    compile_global_func_def(self, self.func_def, globals)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/func_compiler.py", line 22, in compile_global_func_def
    cfg = compile_cfg(func.cfg, builder, builder.inputs(), globals)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/cfg_compiler.py", line 46, in compile_cfg
    blocks[bb] = compile_bb(bb, builder, bb == cfg.entry_bb, globals)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/cfg_compiler.py", line 83, in compile_bb
    dfg = StmtCompiler(globals).compile_stmts(bb.statements, dfg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/stmt_compiler.py", line 44, in compile_stmts
    self.visit(s)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/stmt_compiler.py", line 78, in visit_Expr
    self.expr_compiler.compile_row(node.value, self.dfg)
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 83, in compile_row
    return [self.compile(e, dfg) for e in expr_to_row(expr)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 83, in <listcomp>
    return [self.compile(e, dfg) for e in expr_to_row(expr)]
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 74, in compile
    return self.visit(expr)
           ^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 340, in visit_GlobalCall
    args = [self.visit(arg) for arg in node.args]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 340, in <listcomp>
    args = [self.visit(arg) for arg in node.args]
            ^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 183, in visit_PlaceNode
    self.dfg[subscript.item] = self.visit(subscript.item_expr)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/ast_util.py", line 53, in visit
    return visitor(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/expr_compiler.py", line 185, in visit_PlaceNode
    return self.dfg[node.place]
           ~~~~~~~~^^^^^^^^^^^^
  File "/Users/callum/work_projects/guppy-integration/.venv/lib/python3.11/site-packages/guppylang/compiler/core.py", line 86, in __getitem__
    raise InternalGuppyError(f"Couldn't obtain a port for `{place}`")
guppylang.error.InternalGuppyError: Couldn't obtain a port for `control_index`
```

**Comment by CalMacCQ** [comment]
Now fixed in the latest release
